### ISSUE TITLE
[Bug] Windfreak Microwave Sources behave incorrectly due to low-active trigger

### ISSUE THREAD

**Issue by JohannesWes** [Ulm-IQO/qudi-iqo-modules#105]
### Version

Development

### What is affected by the bug?

module: hardware/mw_source_windfreak_synthhdpro.py, logic/odmr_logic.py

The Windfreak SynthHD Pro that is implemented as a microwave source in the qudi-iqo-modules package is a device with a low-active trigger, that is the triggering starts when the trigger signal becomes low and not if it becomes high.
Due to this, microwaves immediately starts sweeping once "g1" was sent to the microwave in the start_scan() function. This leads to shifts of the ODMR curve to lower frequencies , as discussed in #68 .
I think this problem could occur for any microwave source with low-active trigger.

### When does the bug occur?

odmr scans using microwave generators with low-active triggers.

### How do we replicate the issue?

Connect the windfreak microwave source and perform an ODMR scan.

### Expected behavior

Qudi could implement an option low_active for microwave devices. This option could change the idle state of the NIDAQ card for the digital output that is connected to the trigger input of the microwave.

### Additional Comments

We actually used a SynthNV pro which however should behave identically to the SynthNV pro regarding the trigger, both are low-active. The SynthHD pro is the one implemented in qudi.

### Contact Details

johannes.wesseler@gmail.com

**Comment by NicolasStaudenmaier** [comment]
Thank you for filing this issue @JohannesWes. I have transferred it here from the qudi-core repository. 

For the referenced discussion above please see [qudi-core #68](https://github.com/Ulm-IQO/qudi-core/discussions/68).

**Comment by JohannesWes** [comment]
Of course, will do that next Monday.

**Comment by Neverhorst** [comment]
Does the [trigger_polarity_ni_input branch](https://github.com/Ulm-IQO/qudi-iqo-modules/tree/trigger_polarity_ni_input) resolve this issue, @JohannesWes ? Should we open a PR to merge this to `main`?

**Comment by JohannesWes** [comment]
Despite my promise, I could not check, as we have been moving labs at the
moment so that I didn't have access to the instruments, sorry for that. I
think it should resolve the issue.

Nikolas Tomek ***@***.***> schrieb am Mi., 8. Nov. 2023,
21:12:

**Comment by NicolasStaudenmaier** [comment]
Hi @JohannesWes, did you have a successful lab transfer and did you have time to test the change? If it is working we can close this issue here with a Pull Request of the change.

**Comment by JohannesWes** [comment]
Hi, thank you for the message. While our lab is still in moving boxes, I have opened some and tested it in the office now. Sorry for coming back so late with that, I really appreciate you trying to fix this and realize it's extremely unpolite from my side to have waited so long to test it.

Unfortunately the fix does not work. I get the following message.
HOWEVER: I have created a pull request to this branch with a solution that works for me. I change the idle state of the NI card from LOW to HIGH and use FALLING instead of RISING edges. 

Error while trying to read ODMR scan data from hardware:

nidaqmx.errors.DaqError: Specified inversion cannot be satisfied, because the hardware does not support it.
Source Device: Dev1
Source Terminal: Ctr0InternalOutput
Destination Device: Dev1
Destination Terminal: PFI1

Status Code: -89133
Traceback (most recent call last):

  File "C:\Users\aj92uwef\PycharmProjects\qudi-core\qudi-iqo-modules\src\qudi\logic\odmr_logic.py", line 626, in _scan_odmr_line
    new_counts = scanner.acquire_frame()

  File "C:\Users\aj92uwef\PycharmProjects\qudi-core\qudi-iqo-modules\src\qudi\hardware\ni_x_series\ni_x_series_finite_sampling_input.py", line 473, in acquire_frame
    self.start_buffered_acquisition()

  File "C:\Users\aj92uwef\PycharmProjects\qudi-core\qudi-iqo-modules\src\qudi\hardware\ni_x_series\ni_x_series_finite_sampling_input.py", line 323, in start_buffered_acquisition
    if self._init_sample_clock() < 0:

  File "C:\Users\aj92uwef\PycharmProjects\qudi-core\qudi-iqo-modules\src\qudi\hardware\ni_x_series\ni_x_series_finite_sampling_input.py", line 552, in _init_sample_clock
    ni.system.System().connect_terms(source_terminal=clock_channel,

  File "C:\Users\aj92uwef\PycharmProjects\qudi-core\qudi-env\lib\site-packages\nidaqmx\system\system.py", line 168, in connect_terms
    self._interpreter.connect_terms(

  File "C:\Users\aj92uwef\PycharmProjects\qudi-core\qudi-env\lib\site-packages\nidaqmx\_library_interpreter.py", line 501, in connect_terms
    self.check_for_error(error_code)

  File "C:\Users\aj92uwef\PycharmProjects\qudi-core\qudi-env\lib\site-packages\nidaqmx\_library_interpreter.py", line 6029, in check_for_error
    raise DaqError(extended_error_info, error_code)

**Comment by LukePiewalker** [comment]
@JohannesWes and others.
Since PR#122 is merged now, I suppose this issue can be closed as well, right?
I suppose we can also delete the [trigger_polarity_ni_input branch](https://github.com/Ulm-IQO/qudi-iqo-modules/tree/trigger_polarity_ni_input) as well?

**Comment by JohannesWes** [comment]
From my side, yes.

LukePiewalker ***@***.***> schrieb am Fr., 12. Apr. 2024,
17:15:

**Comment by LukePiewalker** [comment]
Thanks, I will close it.
