### ISSUE TITLE
[Bug] confocal: custom nametag overwrites data from different channels

### ISSUE THREAD

**Issue by qku** [Ulm-IQO/qudi-iqo-modules#151]
### Version

current main

### What is affected by the bug?

confocal toolchain: saving with a custom nametag as introduced by #148 replaces the default nametag. This includes the name of the data channel. Data is saved channel by channel. Therefore, since the filename is identical, the data from the next channel overwrites the data from the previously saved channels.

### When does the bug occur?

- multiple data channels as e.g. when using the scanner dummy
- using a custom save data nametag

### How do we replicate the issue?

Save confocal data with a custom nametag from the dummy configuration.

### Expected behavior

Data from all channels should be saved. This could be achieved e.g. by keeping the channel name in the file name even when a custom tag is used.

**Comment by qku** [comment]
@prithviulm maybe you have a suggestion how to fix this

**Comment by prithviulm** [comment]
Nice catch! I think it makes sense to keep the channel name in the nametag even for a custom nametag.
