### ISSUE TITLE
How to install along qudi-core?

### ISSUE THREAD

**Issue by qku** [Ulm-IQO/qudi-iqo-modules#23]
Hello,
I am trying to start working with the new qudi-core. At the same time, I would like to use some of the modules contained in the qudi-iqo-modules collection. What is the preferred way to install those after installing qudi-core via pip? I could not find any documentation on this and would therefore greatly appreciate assistance! Thank you :)

**Comment by drogenlied** [comment]
Please ask support questions here: https://github.com/Ulm-IQO/qudi-core/discussions

The issue section is only for keeping track of bugs.
