### ISSUE TITLE
[Bug] hardware file and config items of Keysight M8195A

### ISSUE THREAD

**Issue by liuyanulm** [Ulm-IQO/qudi-iqo-modules#34]
### Version

v0.1.0

### What is affected by the bug?

The M8195A hardware file does not contain a config example like the other hardware files.
By looking through the `ConfigOption` related scripts, there is no `missing=error`.
I wrote my config for the M8195A as:
`    awg:

        module.Class: 'awg.keysight_m819x.AWGM819X'

        awg_visa_address: 'TCPIP0::localhost::inst0::INSTR'
`
After activating the hardware module, I got the error report as:
![image](https://user-images.githubusercontent.com/31623230/191460157-9587bb7f-a301-4993-a25b-f39dcfdc1a52.png)

### When does the bug occur?

Loading the M8195A hardware module

### How do we replicate the issue?

maybe the config is not properly written.

### Expected behavior

a successful loading of the hardware and pulsed measurement modules.

### Relevant log output

```shell
Error while loading hardware module: awg
TypeError: Can't instantiate abstract class AWGM819X with abstract methods _compile_bin_samples, _get_digital_ch_cmd, _get_init_output_levels, _get_loaded_seq_catalogue, _get_loaded_seq_name, _get_sequence_control_bin, _set_active_ch, _write_output_on, float_to_sample, get_active_channels, get_constraints, interleaved_wavefile, marker_on, n_ch
Traceback (most recent call last):

  File "C:\qudi_baqis\core\manager.py", line 802, in loadConfigureModule
    self.configureModule(modObj, base, class_name, key, defined_module)

  File "C:\qudi_baqis\core\manager.py", line 591, in configureModule
    instance = modclass(manager=self, name=instanceName, config=configuration)
```

**Comment by timoML** [comment]
Please refer to the given config options for the non-abstract classes, eg. [M8195](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/src/qudi/hardware/awg/keysight_m819x.py#L2094).

**Comment by liuyanulm** [comment]
> Please refer to the given config options for the non-abstract classes, eg. [M8195](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/src/qudi/hardware/awg/keysight_m819x.py#L2094).

Thank you Timo! The problem is solved with your answer. @timoML

**Comment by liuyanulm** [comment]
solved
