### ISSUE TITLE
[Bug] Incorrect config option name in scanning toolchain documentation

### ISSUE THREAD

**Issue by qku** [Ulm-IQO/qudi-iqo-modules#54]
### Version

current main

### What is affected by the bug?

A configuration based on the docs for setting up the scanning toolchain causes a warning that the config option `channels` is not defined for the NI analog output module and default values will be used instead.

### When does the bug occur?

During activation of the hardware module for NI analog output.

### How do we replicate the issue?

Load the example config for the scanning toolchain and activate e.g. the scanner gui.

### Expected behavior

The example config should load without warning.

### Additional Comments

I believe the config option is incorrectly named. The example config says `setpoint_channels`, but it should instead be `channels`.

**Comment by LukePiewalker** [comment]
Thanks for raising this issue @qku. This is now adressed in PR #55.
