### ISSUE TITLE
Tilt correction for Omni scan

### ISSUE THREAD

**Issue by ksenkalla** [Ulm-IQO/qudi-iqo-modules#57]
### Feature Description

For scanning (especially for confocal scans) it would be a nice to have feature that during a scan the tilt of a sample can be automatically corrected. Was already developed on old core but is not included in the whole new omni scan toolchain, since this is something very specific for our way of scanning so far.

If this is developed, the modulatrity of the new omni scan toolchaing needs to survive those changes.

### Related Problem

As of now, there is no tilt correction like there has been in the old core. Honestly, also quite tricky when it comes to "data integrity". How does a 2D scan know about it's position in 3D space?
- loop scans
- pause & resume
- moving (non-scanned) axes during 2D scan

### Considered Alternatives

Since this is something very specific to "Ni Scanning" only, leave it out completely?

**Comment by qku** [comment]
@timoML @LukePiewalker I can possibly test the current state of tilt correction on nidaq hardware. Let me know if it is required!

**Comment by timoML** [comment]
I'm closing this as #98 will be merged shortly.
