### ISSUE TITLE
[Bug] PoiManager can't load files

### ISSUE THREAD

**Issue by timoML** [Ulm-IQO/qudi-iqo-modules#65]
### Version

current main

### What is affected by the bug?

Loading of data causes:

      AttributeError: 'PoiManagerLogic' object has no attribute 'data_directory'
      Traceback (most recent call last):
      File "C:\Users\Software\qudi_newrepo\qudi-iqo-modules\src\qudi\gui\poimanager\poimanagergui.py", line 785, in load_roi
        self._poi_manager_logic().data_directory,

### When does the bug occur?

When hItting "Load ROI" from the PoiManagerGui.

### How do we replicate the issue?

As above.

### Expected behavior

Saved ROIs should be loadable from files.

**Comment by NicolasStaudenmaier** [comment]
Should be fixed with recent PR #76.
