### ISSUE TITLE
[Bug] saving ORMD fitting data

### ISSUE THREAD

**Issue by Maabur** [Ulm-IQO/qudi-iqo-modules#88]
### Version

current main

### What is affected by the bug?

Saving CWODMR fitting data spectra 

### When does the bug occur?

After acquiring a CW spectra and fitting wit a gaussian dip. The data saved has 3 png files two of them contain some mV plots versus the microwave frequency (see enclosed). But I cannot find the fit result data such as the center frequency and the fwhm

### How do we replicate the issue?

Acquire a CW odmr spectra, perform a fit and save.

### Expected behavior

I expect to find somewhere the fitting results data at least on the png file or on the .dat file

### Relevant log output

```shell
none
```

### Additional Comments

![20230828-1719-06_test_ODMR_ai0_range0](https://github.com/Ulm-IQO/qudi-iqo-modules/assets/75795550/06d83f1d-b2fb-4c10-90bf-27859afd99f8)
![20230828-1719-06_test_ODMR_ai1_range0](https://github.com/Ulm-IQO/qudi-iqo-modules/assets/75795550/1ef1611e-460a-4f82-a65c-45d37593b764)
![20230828-1719-06_test_ODMR_pfi3_range0](https://github.com/Ulm-IQO/qudi-iqo-modules/assets/75795550/812cc002-0890-410f-9926-3c501dc491b5)

**Comment by timoML** [comment]
Merged with #99.
