### ISSUE TITLE
[New Feature] scanning probe toolchain: ScanSettings

### ISSUE THREAD

**Issue by qku** [Ulm-IQO/qudi-iqo-modules#90]
### Feature Description

Use separate keyword arguments for axes, range, resolution and frequency in `configure_scan` in `scanning_probe_interface` instead of a dictionary. At the moment, the dictionary entries are not documented.

### Considered Alternatives

- passing a custom data class
- documenting the dictionary entries

**Comment by qku** [comment]
I did some refactoring in my fork and would suggest to amend the interface with a new `ScanSettings` class. I suggest to make use of [dataclass](https://docs.python.org/3/library/dataclasses.html) and roughly implement it the following way:

```
@dataclass(frozen=True)
class ScanSettings:
    """
    Data class representing all settings specifying a scanning probe measurement.

    @param str[] channels: names of scanner channels involved in this scan
    @param str[] axes: names of scanner axes involved in this scan
    @param float[][2] range: inclusive range for each scan axis
    @param int[] resolution: planned number of points for each scan axis
    @param float frequency: Scan pixel frequency of the fast axis
    @param str[] position_feedback_axes: optional, names of axes for which to acquire position
                                         feedback during the scan.
    """

    channels: Sequence[str]
    axes: Sequence[str]
    range: Sequence[tuple[float, float]]
    resolution: Sequence[int]
    frequency: float
    position_feedback_axes: Sequence[str] = field(default_factory=list)
```

**Comment by qku** [comment]
I believe that passing around objects of this class in the scanning probe toolchain can make things a lot easier and facilitate extensions in the future.

**Comment by qku** [comment]
Furthermore, I suggest the following hierarchy:

- at the top: `ScanData`, containing `ScanSettings`, `ScanConstraints`, the actual data, timestamp etc.
- while `ScanSettings` only contains the names of the contributing axes and channels...
- ... `ScanConstraints` actually contains the corresponding `ScannerChannel` and `ScannerAxis` objects
- the individual attributes `resolution`, `frequency` etc. of `ScannerAxis` are implemented as `ScalarConstraint` objects

**Comment by qku** [comment]
Update to that: I actually think that `ScanData` should not contain complete `ScanConstraints` but only the parts it needs (axis units, channel units, channel dtypes).

**Comment by qku** [comment]
@LukePiewalker @Neverhorst I think it would make sense to first talk more about the current implementation in main, so here are two thoughts:

1. `ScanConstraints` contains objects of the classes `ScannerAxis` and `ScannerChannel`, i.e. there is some nesting happening. Should this be avoided? We could consider flattening in that case.
2. Two data classes (without decorator) are currently passed between hardware implementing the interface and any logic/interfuse: `ScanData` and `ScanConstraints`. Something similar is done in the data instream toolchain with the corresponding constraints object. For which cases do we consider this to be a good idea?

The same philosophy can then serve as a guideline for an updated `ScanData` and `ScanConstraints` and a potential `ScanSettings` class.

**Comment by Neverhorst** [comment]
> @LukePiewalker @Neverhorst I think it would make sense to first talk more about the current implementation in main, so here are two thoughts:
> 
> 1. `ScanConstraints` contains objects of the classes `ScannerAxis` and `ScannerChannel`, i.e. there is some nesting happening. Should this be avoided? We could consider flattening in that case.

This may have been a little misunderstanding. There is no general problem in nesting objects, especially in this case where you have multiple instances of the same "thing" (i.e. axes and channels).

> 2. Two data classes (without decorator) are currently passed between hardware implementing the interface and any logic/interfuse: `ScanData` and `ScanConstraints`. Something similar is done in the data instream toolchain with the corresponding constraints object. For which cases do we consider this to be a good idea?
>

For constraints there shouldn't be any problem with this concept. It is generally a read-only data class with some checker functionality. Nobody is mutating this object after creation. This should also be fine for any remote modules.
`ScanData` can be a bit more tricky. It is important that this class has only a single instance (hardware) write to it and all other players are just reading data. The read-only access should mostly work for remote hardware (keep an eye on the data arrays though). While I still think the way it is handled is a good design concept, it is novel for qudi modules as far as I know and should be evaluated in the future. I just wanted to avoid excessive copies of potentially large data arrays.
 
> The same philosophy can then serve as a guideline for an updated `ScanData` and `ScanConstraints` and a potential `ScanSettings` class.

`ScanSettings` should be fine as it is. It's frozen after creation and only accessed read-only with simple data types and especially no `numpy` arrays... the scourge of `rpyc`.
