### ISSUE TITLE
[New Feature] fixed size of time trace window

### ISSUE THREAD

**Issue by Maabur** [Ulm-IQO/qudi-iqo-modules#92]
### Feature Description

The size of the time trace window should stay the same despite the counts displayed. At the moment when the counts changes, the size of the windows slightly increases.

### Considered Alternatives

The font size or the number of digits after the dot could be adjusted instead of changing the size of the window automatically.

**Comment by Neverhorst** [comment]
Hi @Maabur , could you elaborate a bit more please? What exactly is changing and when? The window (the GUI) itself should not change at all. Are you referring to the default auto-scaling of the data plot?

**Comment by Maabur** [comment]
Hello @Neverhorst I will test again with the latest version to see if this problem is happening again. As far as I remember the window (the GUI) is changing. I made the window quite small (less than 1/4 of a 1080p screen) with low counts and then once I reach millions of counts the timetrace windows increases a bit. The fontsize does not changes. I think the window just increases to compensate the increase of the number of digits.

**Comment by timoML** [comment]
We discussed that the increasing window size is desired behavior for some applications. Thus, we tend to leave it this way and close the issue. Is that ok with you @Maabur? If it's creating bigger trouble, we can discuss a change in behavior in one of the next meetings.

**Comment by Maabur** [comment]
yeah sure, sorry for my late answer
