### ISSUE TITLE
[New Feature] digital output for nidaq finite sampling io

### ISSUE THREAD

**Issue by qku** [Ulm-IQO/qudi-iqo-modules#93]
### Feature Description

The finite sampling input/output hardware file for the nidaq currently supports digital input, analog input as well as analog output. For some cases, it would also be useful to be able to use digital outputs.

Is the nidaq capable of synchronizing digital outputs with the inputs the same way it can synchronize analog outputs with all inputs?

It would be appropriate to adjust `FiniteSamplingIOConstraints` in the interface file accordingly to enforce that samples are boolean only for digital channels.

### Related Problem

Digital outputs could be used for auxiliary purposes during scanning. Specifically, they could be used to trigger an initialization laser pulse before the (analog) frequency scan of a resonant laser in a hardware-synchronized manner.

### Considered Alternatives

Analog channels could be used for the same auxiliary purposes. However, those are limited to four per nidaq (maybe more in some models) and are frequently already occupied by three scanner axes and one laser scan axis.

**Comment by LukePiewalker** [comment]
Hey @qku,

Will check and think about this one. Yet, there are some things in the pipeline first. Thanks for your feedback, however!

**Comment by qku** [comment]
Great. It would already helpful to get some estimation on the difficulty of this implementation from someone who wrote code for the nidaq before.

**Comment by qeq-ungar** [comment]
@qku have you been able to activate/control a digital output channel using the finite sampling i/o hardware file? synchronization isn't necessary for my purposes.

**Comment by qku** [comment]
@qeq-ungar not yet, but I also haven't looked into it much yet. I am happy to contribute to implement support however!
